id: A91047D89
title: 'The Sweet Melody to Accomplish Words of Truth: A Prayer for the Long Life
  of the Dharma-Expounding Guide Khenchen Khyenrab Chökyi Özer'
type: translation
pechas:
- I06B80D1B
- IC80CE1C0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:55:58.076715
  last_modified_at: 2023-01-04 12:55:58.076734
  collections:
  - Khyenrab Chökyi Özer Series
  - Works of Tibetan Masters
alignment_to_base:
  I06B80D1B/AB48: DA62
  IC80CE1C0/4B06: DA62
